export { getCurrentInstance } from './component'
export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { createTextNode, createVNode } from './vnode'
export { provide, inject } from './apiInject'
